// src/seeder/mission.seeder.ts
import { Injectable } from '@nestjs/common';
import { KyselyService } from 'src/kysely/kysely.service';
import { TitleType } from 'src/kysely/types';

@Injectable()
export class TitleSeeder {
  constructor(private readonly kyselyService: KyselyService) {}

  private get db() {
    return this.kyselyService.connection;
  }

  async seed() {
    const titles: Array<{
      name: string;
      emoji: string;
      explanation: string;
      condition: number;
      condition_description: string;
      type: TitleType;
    }> = [
      // login count
      {
        name: '來一下就走',
        emoji: '👋📲',
        explanation: '你來過一次，系統默默記下來了。',
        condition: 1,
        condition_description: '累積登入 1 次',
        type: 'LOGIN_TOTAL',
      },
      {
        name: '時不時滑一下',
        emoji: '📱🌀',
        explanation: '你不常來，但每次來都有點事。',
        condition: 5,
        condition_description: '累積登入 5 次',
        type: 'LOGIN_TOTAL',
      },
      {
        name: '小有默契',
        emoji: '🤝📆',
        explanation: '你跟這個App開始有點默契了。',
        condition: 10,
        condition_description: '累積登入 10 次',
        type: 'LOGIN_TOTAL',
      },
      {
        name: '登入有感情',
        emoji: '🫶📲',
        explanation: '你來得夠多次，開始有點熟悉的感覺了。',
        condition: 25,
        condition_description: '累積登入 25 次',
        type: 'LOGIN_TOTAL',
      },
      {
        name: '你是不是住這',
        emoji: '🏠📱',
        explanation: '你來得太自然了，像住在這裡。',
        condition: 50,
        condition_description: '累積登入 50 次',
        type: 'LOGIN_TOTAL',
      },
      {
        name: '老帳號的尊嚴',
        emoji: '🧓📆',
        explanation: '你不是新手，你是資深會員。',
        condition: 100,
        condition_description: '累積登入 100 次',
        type: 'LOGIN_TOTAL',
      },
      {
        name: '登入骨灰級',
        emoji: '⚱️📲',
        explanation: '你登入的頻率，連演算法都感動了。',
        condition: 200,
        condition_description: '累積登入 200 次',
        type: 'LOGIN_TOTAL',
      },
      {
        name: '登入週年慶',
        emoji: '🎉📅',
        explanation: '你登入的次數已經過了一整年。重複，是一種信仰。',
        condition: 365,
        condition_description: '累積登入 365 次',
        type: 'LOGIN_TOTAL',
      },
      // login streak (consecutive days)
      {
        name: '被演算法吸住了',
        emoji: '🧲📲',
        explanation: '你本來想看一眼，結果每天都來。',
        condition: 5,
        condition_description: '連續登入5天',
        type: 'LOGIN_STREAK',
      },
      {
        name: '打卡老司機',
        emoji: '🚕',
        explanation: '不是我想來，是身體自己打開App了。',
        condition: 10,
        condition_description: '連續登入10天',
        type: 'LOGIN_STREAK',
      },
      {
        name: '登入當修行',
        emoji: '🧘📆',
        explanation: '你每天來一次，彷彿在進行某種儀式。',
        condition: 15,
        condition_description: '連續登入15天',
        type: 'LOGIN_STREAK',
      },
      {
        name: '登入變本能',
        emoji: '🧠⏰',
        explanation: '你根本沒意識到自己每天都會出現。',
        condition: 30,
        condition_description: '連續登入30天',
        type: 'LOGIN_STREAK',
      },
      {
        name: '打卡天尊',
        emoji: '📆👑',
        explanation: '連續登入60天，佛系打卡變成修行大業。',
        condition: 60,
        condition_description: '連續登入60天',
        type: 'LOGIN_STREAK',
      },
      {
        name: '打卡週期神獸',
        emoji: '🌕📲',
        explanation: '你連續半年的韌性，連月亮都佩服了。',
        condition: 90,
        condition_description: '連續登入90天',
        type: 'LOGIN_STREAK',
      },
      {
        name: '你還好嗎',
        emoji: '😶📆',
        explanation: '我們不是質疑你，我們是真心關心你。',
        condition: 365,
        condition_description: '連續登入365天',
        type: 'LOGIN_STREAK',
      },
      // subscription
      {
        name: '真愛的開端',
        emoji: '💞',
        explanation: '訂閱了？這就是真愛的開始。',
        condition: 1,
        condition_description: '第一次訂閱',
        type: 'SUBSCRIPTION',
      },
      // clicking news
      {
        name: '點開看一下啦',
        emoji: '👀📰',
        explanation: '只是想看一下內容，結果打開新世界。',
        condition: 1,
        condition_description: '點擊 1 篇文章',
        type: 'CLICK_ARTICLE_TOTAL',
      },
      {
        name: '一篇接一篇',
        emoji: '📖📖',
        explanation: '你只是滑一下，結果滑出五篇。',
        condition: 5,
        condition_description: '點擊超過 5 篇文章',
        type: 'CLICK_ARTICLE_TOTAL',
      },
      {
        name: '越點越不對勁',
        emoji: '🧠📲',
        explanation: '一篇接一篇，你越看越不對勁。',
        condition: 20,
        condition_description: '點擊超過 20 篇文章',
        type: 'CLICK_ARTICLE_TOTAL',
      },
      {
        name: '嘴巴備料王',
        emoji: '🍽️🗯️',
        explanation: '你不是在看新聞，你在為留言做功課。',
        condition: 50,
        condition_description: '點擊超過 50 篇文章',
        type: 'CLICK_ARTICLE_TOTAL',
      },
      {
        name: '點到飛起來',
        emoji: '🚀📚',
        explanation: '你已經不是在看新聞，是在進行腦內特訓。',
        condition: 100,
        condition_description: '點擊超過 100 篇文章',
        type: 'CLICK_ARTICLE_TOTAL',
      },
      {
        name: '資訊高速公路狂飆者',
        emoji: '🚗💨📰',
        explanation: '你在新聞裡狂飆，AI都快跟不上你了。',
        condition: 200,
        condition_description: '點擊超過 200 篇文章',
        type: 'CLICK_ARTICLE_TOTAL',
      },
      {
        name: '讀到走火入魔',
        emoji: '📚🔥',
        explanation: '你今天到底看了幾篇？AI都開始替你擔心視力了。',
        condition: 300,
        condition_description: '點擊超過 300 篇文章',
        type: 'CLICK_ARTICLE_TOTAL',
      },
      {
        name: '點出知識焦慮',
        emoji: '📉📚',
        explanation: '你越點越焦慮，但就是停不下來。',
        condition: 500,
        condition_description: '點擊超過 500 篇文章',
        type: 'CLICK_ARTICLE_TOTAL',
      },
      // comments (count)
      {
        name: '手滑發出去的',
        emoji: '🤏📤',
        explanation: '你可能只是想打幾個字，結果就上了。',
        condition: 1,
        condition_description: '發表1則留言',
        type: 'COMMENT_TOTAL',
      },
      {
        name: '語氣試水溫',
        emoji: '🌡️💬',
        explanation: '你開始測試哪種語氣最容易被戰爆。',
        condition: 5,
        condition_description: '發表5則留言',
        type: 'COMMENT_TOTAL',
      },
      {
        name: '鍵盤已熱身',
        emoji: '⌨️🔥',
        explanation: '你打得不多，但每句都想讓人回嘴。',
        condition: 20,
        condition_description: '發表20則留言',
        type: 'COMMENT_TOTAL',
      },
      {
        name: '看到標題就想嘴',
        emoji: '😤📰',
        explanation: '你連內文都還沒讀完，留言已經打完一半了。',
        condition: 30,
        condition_description: '發表30則留言',
        type: 'COMMENT_TOTAL',
      },
      {
        name: '留言成癮者',
        emoji: '🧠💬',
        explanation: '你本來只是看看，現在看到標題手就癢。',
        condition: 50,
        condition_description: '發表50則留言',
        type: 'COMMENT_TOTAL',
      },
      {
        name: '嘴砲王',
        emoji: '🗣️💥',
        explanation: '留言數破百，場場嘴到高潮迭起。',
        condition: 100,
        condition_description: '發表100則留言',
        type: 'COMMENT_TOTAL',
      },
      {
        name: '嘴到宇宙邊界',
        emoji: '🚀🗨️',
        explanation: '你留言的速度，連AI都來不及回。',
        condition: 200,
        condition_description: '發表200則留言',
        type: 'COMMENT_TOTAL',
      },
      {
        name: '留言已成反射動作',
        emoji: '🧠⚡',
        explanation: '你看到空白輸入框，大腦就自動開機。',
        condition: 400,
        condition_description: '發表400則留言',
        type: 'COMMENT_TOTAL',
      },
      {
        name: '留言區馬桶神獸',
        emoji: '🚽🐉',
        explanation: '每天都來、從不缺席、永遠嘴得出水準。',
        condition: 600,
        condition_description: '發表600則留言',
        type: 'COMMENT_TOTAL',
      },
      // getting a response
      {
        name: '有人鳥我了',
        emoji: '🫢🗨️',
        explanation: '第一次有人回你留言，你有點感動。',
        condition: 1,
        condition_description: '留言被回覆1次',
        type: 'COMMENT_REPLY_TOTAL',
      },
      {
        name: '留言有回音',
        emoji: '🔊🗯️',
        explanation: '你丟了一句話出去，結果真的有幾人回你。',
        condition: 5,
        condition_description: '累積5次留言被回覆',
        type: 'COMMENT_REPLY_TOTAL',
      },
      {
        name: '嘴出第一波水花',
        emoji: '💦🗣️',
        explanation: '你講的話開始激起一點討論小浪花。',
        condition: 10,
        condition_description: '累積10次留言被回覆',
        type: 'COMMENT_REPLY_TOTAL',
      },
      {
        name: '嘴到被圍毆',
        emoji: '👊🧠',
        explanation: '你一留言，大家就衝來討論（或開噴）。',
        condition: 30,
        condition_description: '累積30次留言被回覆',
        type: 'COMMENT_REPLY_TOTAL',
      },
      {
        name: '嘴出高流量現場',
        emoji: '📈💬',
        explanation: '你根本是一人留言專區，大家都來你的樓下集合。',
        condition: 50,
        condition_description: '累積50次留言被回覆',
        type: 'COMMENT_REPLY_TOTAL',
      },
      // getting liked
      {
        name: '有人按讚耶',
        emoji: '👍😳',
        explanation: '你第一次被認同，心裡小鹿亂撞。',
        condition: 1,
        condition_description: '留言獲得1次按讚',
        type: 'COMMENT_LIKE_TOTAL',
      },
      {
        name: '有被聽見的感覺',
        emoji: '🫶🗨️',
        explanation: '你講的大家真的有在看，還順便點了讚。',
        condition: 10,
        condition_description: '累積10次留言按讚',
        type: 'COMMENT_LIKE_TOTAL',
      },
      {
        name: '留言區清流',
        emoji: '💧🗯️',
        explanation: '你是戰火中的一股理性，偶爾還有點幽默感。',
        condition: 30,
        condition_description: '累積30次留言按讚',
        type: 'COMMENT_LIKE_TOTAL',
      },
      {
        name: '留言區的舒壓小品',
        emoji: '💆🗯️',
        explanation: '你講話有內容又不刺耳，大家都想多看幾句。',
        condition: 50,
        condition_description: '累積50次留言按讚',
        type: 'COMMENT_LIKE_TOTAL',
      },
      {
        name: '留言留到出圈',
        emoji: '💬',
        explanation: '一開口，留言區直接爆紅，還有人截圖傳長輩群組。',
        condition: 100,
        condition_description: '留言拿到100個讚',
        type: 'COMMENT_LIKE_TOTAL',
      },
      {
        name: '留言區的發光體',
        emoji: '🌟🗨️',
        explanation: '不管什麼主題，你總能貼中關鍵還不惹火。',
        condition: 200,
        condition_description: '累積200次留言按讚',
        type: 'COMMENT_LIKE_TOTAL',
      },
      {
        name: '嘴出一片和平',
        emoji: '🕊️🗣️',
        explanation: '你的留言讓雙方都冷靜下來，奇蹟本蹟。',
        condition: 400,
        condition_description: '累積400次留言按讚',
        type: 'COMMENT_LIKE_TOTAL',
      },
      {
        name: '留言區的心靈導師',
        emoji: '🧘💬',
        explanation: '你講話像在冥想，連酸民都點讚。',
        condition: 600,
        condition_description: '累積600次留言按讚',
        type: 'COMMENT_LIKE_TOTAL',
      },
      {
        name: '嘴出宇宙共鳴',
        emoji: '🌌❤️',
        explanation: '你的留言超越立場，直接進入人類情感核心。',
        condition: 1000,
        condition_description: '累積1000次留言按讚',
        type: 'COMMENT_LIKE_TOTAL',
      },
      // getting disliked
      {
        name: '被踩的感覺是這樣喔',
        emoji: '👣😐',
        explanation: '你第一次體驗到留言區的現實面。',
        condition: 1,
        condition_description: '收到1次點踩',
        type: 'COMMENT_DISLIKE_TOTAL',
      },
      {
        name: '這不是我原本的語氣',
        emoji: '🫣📉',
        explanation: '你只是講話比較直接，結果被當戰犯。',
        condition: 10,
        condition_description: '累積10次點踩',
        type: 'COMMENT_DISLIKE_TOTAL',
      },
      {
        name: '嘴到連同溫層都不挺',
        emoji: '🧨🫥',
        explanation: '你本來在自家陣營，現在沒人想認你。',
        condition: 30,
        condition_description: '累積30次點踩',
        type: 'COMMENT_DISLIKE_TOTAL',
      },
      {
        name: '踩不死的嘴',
        emoji: '💀🗣️',
        explanation: '你越被踩，越想講。你是逆風嘴砲機器。',
        condition: 50,
        condition_description: '累積50次點踩',
        type: 'COMMENT_DISLIKE_TOTAL',
      },
      {
        name: '踩爽的是你吧',
        emoji: '🫠👎',
        explanation: '你越被罵越開心，這是什麼奇怪體質？',
        condition: 100,
        condition_description: '累積100次點踩',
        type: 'COMMENT_DISLIKE_TOTAL',
      },
      {
        name: '引戰大師兄-1',
        emoji: '🔥🐉',
        explanation: '你的留言引爆戰火，AI都來不及滅火。',
        condition: 150,
        condition_description: '累積150次點踩',
        type: 'COMMENT_DISLIKE_TOTAL',
      },
      {
        name: '嘴到被全村點踩',
        emoji: '🏘️👎',
        explanation: '你被留言區集體送上火刑架。',
        condition: 250,
        condition_description: '累積250次點踩',
        type: 'COMMENT_DISLIKE_TOTAL',
      },
      {
        name: '前世造的孽',
        emoji: '👻🗯️',
        explanation: '你說的每一句，都是前世造的孽。',
        condition: 500,
        condition_description: '累積500次點踩',
        type: 'COMMENT_DISLIKE_TOTAL',
      },
      {
        name: '引戰大師兄-2',
        emoji: '🔥🐉',
        explanation: '你的留言引爆戰火，AI都來不及滅火。',
        condition: 100,
        condition_description: '留言被點踩超過100次',
        type: 'COMMENT_DISLIKE_TOTAL',
      },
      // change profile
      {
        name: '人設成精',
        emoji: '🧞‍♂️',
        explanation: '個人資料一改再改，連你自己都快認不出你自己了。',
        condition: 5,
        condition_description: '更改暱稱 + 頭像 + 立場 + 身分共超過5次',
        type: 'PROFILE_CHANGE_TOTAL',
      },
      // clickbait
      {
        name: '釣魚初體驗',
        emoji: '🐟👶',
        explanation: '你點了第一篇釣魚文，恭喜入坑！',
        condition: 1,
        condition_description: '點擊數達1',
        type: 'CLICKBAIT_CLICK_TOTAL',
      },
      {
        name: '點擊自虐狂',
        emoji: '😵‍💫🖱️',
        explanation: '明知是騙人的標題，但你控制不了手指。',
        condition: 20,
        condition_description: '點擊數達20',
        type: 'CLICKBAIT_CLICK_TOTAL',
      },
      {
        name: '標題的狗',
        emoji: '🐶📰',
        explanation: '標題一丟，你就撿回來了。',
        condition: 50,
        condition_description: '點擊數達50',
        type: 'CLICKBAIT_CLICK_TOTAL',
      },
      {
        name: '點擊受害者協會會長',
        emoji: '📛📢',
        explanation: '你不是唯一受害者，但你是最資深的那位。',
        condition: 100,
        condition_description: '點擊數達100',
        type: 'CLICKBAIT_CLICK_TOTAL',
      },
      {
        name: '被演算法養大的孩子',
        emoji: '👶📲',
        explanation: '你點的不是文章，是推薦系統的愛。',
        condition: 200,
        condition_description: '點擊數達200',
        type: 'CLICKBAIT_CLICK_TOTAL',
      },
      // cross-analysis
      {
        name: 'AI初體驗',
        emoji: '🤖✨',
        explanation: '你讓AI幫你比對新聞，世界從此不同。',
        condition: 1,
        condition_description: '第一次使用AI分析功能',
        type: 'AI_ANALYSIS_TOTAL',
      },
      {
        name: '我不是在挑語病',
        emoji: '🙃🔍',
        explanation: '我只是在比較兩篇誰比較會拐彎抹角。',
        condition: 5,
        condition_description: '使用AI分析功能5次以上',
        type: 'AI_ANALYSIS_TOTAL',
      },
      {
        name: '雞同鴨講之AI觀察日記',
        emoji: '🐔🦆',
        explanation: '明明是同一件事，怎麼講得像不同宇宙？',
        condition: 10,
        condition_description: '使用AI分析功能10次以上',
        type: 'AI_ANALYSIS_TOTAL',
      },
      {
        name: 'AI迷弟',
        emoji: '🤖❤️',
        explanation: '你點AI分析的次數，讓AI都臉紅了。',
        condition: 20,
        condition_description: '使用AI分析功能超過20次',
        type: 'AI_ANALYSIS_TOTAL',
      },
      {
        name: '這不是八點檔？',
        emoji: '🎭📺',
        explanation: '你發現新聞敘事越來越像連續劇。',
        condition: 40,
        condition_description: '使用AI分析功能40次以上',
        type: 'AI_ANALYSIS_TOTAL',
      },
      {
        name: '視角探索者',
        emoji: '🧭📰',
        explanation: '你開始發現，同一件事，不同媒體說法差很大。',
        condition: 60,
        condition_description: '使用AI分析功能60次以上',
        type: 'AI_ANALYSIS_TOTAL',
      },
      {
        name: '語境考古學家',
        emoji: '🪶📚',
        explanation: '你像在挖掘新聞語言背後的歷史與立場。',
        condition: 100,
        condition_description: '使用AI分析功能100次以上',
        type: 'AI_ANALYSIS_TOTAL',
      },
      {
        name: '新聞哲學家',
        emoji: '👓📖',
        explanation: '你不只問「發生了什麼」，你問「為什麼這樣寫」。',
        condition: 150,
        condition_description: '使用AI分析功能150次以上',
        type: 'AI_ANALYSIS_TOTAL',
      },
      // quirky activities
      {
        name: '英雄轉生系統啟動',
        emoji: '👤',
        explanation: '頭像一換，人設重練，帥到連AI都認不出你。',
        condition: 1,
        condition_description: '更換一次頭像',
        type: 'AVATAR_CHANGE_TOTAL',
      },
      // like news
      {
        name: '這則不錯讚一下',
        emoji: '📰👍',
        explanation: '你對某則新聞產生了一絲共鳴，決定點下人生第一讚。',
        condition: 1,
        condition_description: '對新聞按讚 1 次',
        type: 'NEWS_LIKE_TOTAL',
      },
      {
        name: '按讚純為諷刺',
        emoji: '🫠❤️',
        explanation: '這新聞太離譜，不按讚對不起自己。',
        condition: 5,
        condition_description: '對新聞按讚 5 次',
        type: 'NEWS_LIKE_TOTAL',
      },
      {
        name: '新聞當迷因看',
        emoji: '📺🤣',
        explanation: '你不是在看新聞，你是在看喜劇。',
        condition: 10,
        condition_description: '對新聞按讚 10 次',
        type: 'NEWS_LIKE_TOTAL',
      },
      {
        name: '我只讚爛新聞',
        emoji: '🗑️❤️',
        explanation: '只要標題夠爛，我就幫它上熱門。',
        condition: 25,
        condition_description: '對新聞按讚 25 次',
        type: 'NEWS_LIKE_TOTAL',
      },
      {
        name: '讚到演算法以為你有立場',
        emoji: '🧠🪤',
        explanation: '你只是亂讚，但系統已經幫你貼標籤了。',
        condition: 100,
        condition_description: '對新聞按讚 100 次',
        type: 'NEWS_LIKE_TOTAL',
      },
      // dislike news
      {
        name: '這什麼爛新聞',
        emoji: '🤨👎',
        explanation: '你第一次對新聞表達了「夠了」的情緒。',
        condition: 1,
        condition_description: '對新聞按下 1 次「不喜歡」',
        type: 'NEWS_DISLIKE_TOTAL',
      },
      {
        name: '我氣到手癢',
        emoji: '😤📱',
        explanation: '你不是隨便按，是按下去才會比較舒服。',
        condition: 5,
        condition_description: '對新聞按下 5 次「不喜歡」',
        type: 'NEWS_DISLIKE_TOTAL',
      },
      {
        name: '不按踩我會內傷',
        emoji: '😮‍💨👎',
        explanation: '你按的是怒，吐的是氣。',
        condition: 10,
        condition_description: '對新聞按下 10 次「不喜歡」',
        type: 'NEWS_DISLIKE_TOTAL',
      },
      {
        name: '這也能叫新聞？',
        emoji: '🗞️❓👎',
        explanation: '你開始對新聞本身產生哲學疑問。',
        condition: 20,
        condition_description: '對新聞按下 20 次「不喜歡」',
        type: 'NEWS_DISLIKE_TOTAL',
      },
      {
        name: '這記者欠我一分鐘',
        emoji: '⌛👎',
        explanation: '看完只想說：浪費我時間。',
        condition: 40,
        condition_description: '對新聞按下 40 次「不喜歡」',
        type: 'NEWS_DISLIKE_TOTAL',
      },
      {
        name: '這篇到底審稿了沒',
        emoji: '🔍📝👎',
        explanation: '錯字、亂碼、邏輯斷裂。你怒得很有道理。',
        condition: 60,
        condition_description: '對新聞按下 60 次「不喜歡」',
        type: 'NEWS_DISLIKE_TOTAL',
      },
      {
        name: '這 AI 寫的吧',
        emoji: '🧠💤👎',
        explanation: '沒靈魂、沒邏輯、沒人味。',
        condition: 65,
        condition_description: '對新聞按下 65 次「不喜歡」',
        type: 'NEWS_DISLIKE_TOTAL',
      },
      {
        name: '新聞敗壞觀察員',
        emoji: '🧓📉👎',
        explanation: '每天看新聞都覺得世界要滅亡了。',
        condition: 75,
        condition_description: '對新聞按下 75 次「不喜歡」',
        type: 'NEWS_DISLIKE_TOTAL',
      },
      {
        name: '這在騙點擊還是騙人生',
        emoji: '🧠🕳️👎',
        explanation: '點進去的是新聞，出來的是靈魂空洞。',
        condition: 100,
        condition_description: '對新聞按下 100 次「不喜歡」',
        type: 'NEWS_DISLIKE_TOTAL',
      },
      // Share news
      {
        name: '你看這個',
        emoji: '👀🗞️',
        explanation: '你第一次覺得這新聞值得分享給別人看看。',
        condition: 1,
        condition_description: '分享 1 次新聞',
        type: 'NEWS_SHARE_TOTAL',
      },
      {
        name: '這不能只有我看到',
        emoji: '😳📤',
        explanation: '你覺得這則新聞太震撼，必須讓更多人知道。',
        condition: 5,
        condition_description: '分享 5 次新聞',
        type: 'NEWS_SHARE_TOTAL',
      },
      {
        name: '轉發小能手',
        emoji: '📲💬',
        explanation: '你開始穩定輸出新聞給朋友群組。',
        condition: 10,
        condition_description: '分享 10 次新聞',
        type: 'NEWS_SHARE_TOTAL',
      },
      {
        name: '資訊傳教士',
        emoji: '🙏🌐',
        explanation: '你不只是分享，你是在傳遞真相。',
        condition: 20,
        condition_description: '分享 20 次新聞',
        type: 'NEWS_SHARE_TOTAL',
      },
      {
        name: '人形新聞 API',
        emoji: '🧠🌐🗞️',
        explanation: '你就是大家的新聞即時通知系統。',
        condition: 30,
        condition_description: '分享 30 次新聞',
        type: 'NEWS_SHARE_TOTAL',
      },
      {
        name: '我就是演算法本人',
        emoji: '🎯🧠🌀',
        explanation: '你比演算法還懂朋友想看什麼新聞。',
        condition: 50,
        condition_description: '分享 50 次新聞',
        type: 'NEWS_SHARE_TOTAL',
      },
      // vote
      {
        name: '參與的第一步',
        emoji: '👣🗳️',
        explanation: '你選擇不只是旁觀，而是參與。',
        condition: 1,
        condition_description: '對新聞相關問題投票 1 次',
        type: 'NEWS_VOTE_TOTAL',
      },
      {
        name: '用選項表態',
        emoji: '🖱️🧭',
        explanation: '你相信，選擇本身就是一種方向。',
        condition: 3,
        condition_description: '對新聞相關問題投票 3 次',
        type: 'NEWS_VOTE_TOTAL',
      },
      {
        name: '我不是路人',
        emoji: '🚶‍♂️🗳️',
        explanation: '你選擇參與，而不是袖手旁觀。',
        condition: 10,
        condition_description: '對新聞相關問題投票 10 次',
        type: 'NEWS_VOTE_TOTAL',
      },
      {
        name: '公民意識養成中',
        emoji: '🧠📈',
        explanation: '你在一次次選擇中，成為更成熟的自己。',
        condition: 20,
        condition_description: '對新聞相關問題投票 20 次',
        type: 'NEWS_VOTE_TOTAL',
      },
      {
        name: '投票使我自由',
        emoji: '🗽🗳️',
        explanation: '你知道每一票都是一種參與。',
        condition: 40,
        condition_description: '對新聞相關問題投票 40 次',
        type: 'NEWS_VOTE_TOTAL',
      },
      {
        name: '用投票參與世界',
        emoji: '🌍🗳️',
        explanation: '你的每一票，都是對世界的回應。',
        condition: 70,
        condition_description: '對新聞相關問題投票 70 次',
        type: 'NEWS_VOTE_TOTAL',
      },
      {
        name: '我投故我在',
        emoji: '🗳️🧘‍♂️',
        explanation: '你的選擇，是內心價值的鏡子。',
        condition: 100,
        condition_description: '對新聞相關問題投票 100 次',
        type: 'NEWS_VOTE_TOTAL',
      },
      // Follow journalists
      {
        name: '我想聽你怎麼說',
        emoji: '👂🖋️',
        explanation: '你選擇不只是看新聞，而是關注說故事的人。',
        condition: 1,
        condition_description: '追蹤 1 位記者',
        type: 'JOURNALIST_FOLLOW_TOTAL',
      },
      {
        name: '開始建立信任名單',
        emoji: '📋🤝',
        explanation: '你在記者中，找到值得信任的聲音。',
        condition: 3,
        condition_description: '追蹤 3 位記者',
        type: 'JOURNALIST_FOLLOW_TOTAL',
      },
      {
        name: '我在乎誰寫的',
        emoji: '🧠✍️',
        explanation: '你知道，觀點來自人，而不是標題。',
        condition: 5,
        condition_description: '追蹤 5 位記者',
        type: 'JOURNALIST_FOLLOW_TOTAL',
      },
      {
        name: '記者觀察家',
        emoji: '🔎🧑‍💼',
        explanation: '你開始看見，不同記者筆下的世界差異。',
        condition: 10,
        condition_description: '追蹤 10 位記者',
        type: 'JOURNALIST_FOLLOW_TOTAL',
      },
      {
        name: '我支持這些聲音',
        emoji: '📢💙',
        explanation: '你用追蹤的方式，支持公共討論的品質。',
        condition: 15,
        condition_description: '追蹤 15 位記者',
        type: 'JOURNALIST_FOLLOW_TOTAL',
      },
      {
        name: '人是我選的，文我也看',
        emoji: '🧑‍💻🗞️',
        explanation: '你的閱讀習慣，已經與信任建立連結。',
        condition: 20,
        condition_description: '追蹤 20 位記者',
        type: 'JOURNALIST_FOLLOW_TOTAL',
      },
      // search
      {
        name: '偵探的起點',
        emoji: '🕵️‍♀️🔍',
        explanation: '你開始追蹤資料，而不是只看內容。',
        condition: 1,
        condition_description: '搜尋 1 次',
        type: 'SEARCH_TOTAL',
      },
      {
        name: '我查的不是新聞，是脈絡',
        emoji: '🕸️📚',
        explanation: '標題只是表面，你已經在找底層邏輯。',
        condition: 10,
        condition_description: '搜尋 10 次',
        type: 'SEARCH_TOTAL',
      },
      {
        name: '別人滑抖音，我查新聞',
        emoji: '📈🧃',
        explanation: '你不是在滑，而是在提高自己的新聞素養。',
        condition: 30,
        condition_description: '搜尋 30 次',
        type: 'SEARCH_TOTAL',
      },
      {
        name: '搜尋界的福爾摩斯',
        emoji: '🧠🕵️‍♂️',
        explanation: '你搜尋的速度快到小編都怕。',
        condition: 50,
        condition_description: '搜尋 50 次',
        type: 'SEARCH_TOTAL',
      },
      {
        name: '整個媒體圈都被你查過了',
        emoji: '🗞️🕳️',
        explanation: '你已經接近全知狀態，媒體本人都怕你。',
        condition: 100,
        condition_description: '搜尋 100 次',
        type: 'SEARCH_TOTAL',
      },
      // Claim rewards
      {
        name: '腦袋不是裝飾品',
        emoji: '🧠🪞',
        explanation: '你居然真的有在動腦，我們以為那只是散熱裝置。',
        condition: 1,
        condition_description: '你領了 1 次腦袋，終於不是裝可愛了。',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '你連點腦袋都不嫌累',
        emoji: '🖱️🧠',
        explanation: '這年頭肯動一下滑鼠就能當英雄。',
        condition: 5,
        condition_description: '5 次點擊，我們先給你發張獎狀。',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '靠領獎也能變聰明？',
        emoji: '🎁🤯',
        explanation: '你是不是覺得 IQ 像遊戲等級一樣會升？',
        condition: 10,
        condition_description: '10 次了，你是不是覺得自己快會飛？',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '腦袋領好領滿',
        emoji: '🍽️🧠',
        explanation: '知識當飯吃？你現在是吃到飽模式。',
        condition: 20,
        condition_description: '20 顆腦袋，你應該有點飽了吧？',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '知識的基本尊重',
        emoji: '📚👍',
        explanation: '看得出來你對腦袋是有點尊重的。',
        condition: 30,
        condition_description: '30 次，好學生出現了。',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '請問你有在上班嗎？',
        emoji: '🏢❓',
        explanation: '一天到晚在領腦袋，你老闆知道嗎？',
        condition: 40,
        condition_description: '40 次，建議你打卡一下。',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '再領下去你要變天才了',
        emoji: '🌟🧠',
        explanation: '這不是平台，這是你的人生加速器。',
        condition: 50,
        condition_description: '50 次，你的額頭應該在發光。',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '點腦當興趣',
        emoji: '🎯🧠',
        explanation: '有些人打電動，你點腦袋，各取所需。',
        condition: 60,
        condition_description: '60 次，你已經不是路人了。',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '腦袋富翁',
        emoji: '💰🧠',
        explanation: '你快可以開 NFT 腦袋交易所了。',
        condition: 75,
        condition_description: '75 顆腦袋，記得報稅。',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '知識爆肝王',
        emoji: '💻👀',
        explanation: '你這不是學習，是在熬煉神魂。',
        condition: 90,
        condition_description: '90 次，你的電腦都熱到能煎蛋了。',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '百腦齊發',
        emoji: '🎉🧠🧠',
        explanation: '你不是人，是腦袋的集合體。',
        condition: 100,
        condition_description: '100 次，你是不是會發光了？',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '點腦職人',
        emoji: '🧰🧠',
        explanation: '你把這當正職是不是？要不要報薪資？',
        condition: 150,
        condition_description: '150 次，你該加入工會了。',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '知識倉鼠',
        emoji: '🐹📚',
        explanation: '每天點腦袋，跑輪子也追不上你。',
        condition: 200,
        condition_description: '200 次，看來你很怕無知。',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '腦袋批發商',
        emoji: '📦🧠',
        explanation: '你是準備轉賣給別人嗎？',
        condition: 250,
        condition_description: '250 次，該開店了。',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '點到懷疑人生',
        emoji: '🤯❓',
        explanation: '你是不是有點空虛？',
        condition: 300,
        condition_description: '300 次，你還記得為什麼開始嗎？',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '腦袋已經具現化',
        emoji: '🧠✨',
        explanation: '你的思考已經脫離肉體限制。',
        condition: 350,
        condition_description: '350 次，你的腦袋應該會說話了。',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '升天神腦',
        emoji: '🛐🧠',
        explanation: '我們已經在你腳下朝拜。',
        condition: 400,
        condition_description: '400 次，你是神腦沒錯了。',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '你不是在領腦，是在召喚異界智慧體',
        emoji: '📡👁️',
        explanation: '我們懷疑你已經跟外星人連線。',
        condition: 450,
        condition_description: '450 次，你的 Wi-Fi 應該直通銀河。',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '學術界噩夢',
        emoji: '📚👻',
        explanation: '教授看到你都會怕。',
        condition: 500,
        condition_description: '500 次，論文都不敢騙你了。',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '知識黑幫老大',
        emoji: '🧠💼',
        explanation: '你不是在學習，你在經營勢力。',
        condition: 550,
        condition_description: '550 次，知識界現在靠你罩。',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '點腦內建外掛',
        emoji: '🧠🔌',
        explanation: '你是不是偷偷接了 GPT？',
        condition: 600,
        condition_description: '600 次，你到底是誰？',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '智慧教主',
        emoji: '📿🧠',
        explanation: '你現在是腦袋教的創始人。',
        condition: 650,
        condition_description: '650 次，我們都叫你師父。',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '資訊異能者',
        emoji: '🧠🌀',
        explanation: '你可能已經能預測未來。',
        condition: 700,
        condition_description: '700 次，你腦袋快破防了。',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '知識轉生者',
        emoji: '♻️🧠',
        explanation: '你可能已經經歷過八世輪迴。',
        condition: 750,
        condition_description: '750 次，請問你轉生到哪個伺服器？',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '腦袋 NFT 藝術家',
        emoji: '🎨🧠',
        explanation: '你這麼多腦袋，不如鑄幣了。',
        condition: 800,
        condition_description: '800 次，要不要上鏈一下？',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '宇宙級資料掠奪者',
        emoji: '🌌🧠🧲',
        explanation: '你不是領腦，是在吞星球。',
        condition: 850,
        condition_description: '850 次，地球快不夠你用了。',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '終極知識黑洞',
        emoji: '🕳️🧠',
        explanation: '你連我們的資料都吸光了。',
        condition: 900,
        condition_description: '900 次，請別把我們資料庫吃掉。',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '全自動點腦機器人',
        emoji: '🤖🧠',
        explanation: '你還是人類嗎？我們開始懷疑了。',
        condition: 925,
        condition_description: '925 次，是不是在用腳本？',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '腦袋點到手抽筋',
        emoji: '✋😵',
        explanation: '你應該去看復健科。',
        condition: 950,
        condition_description: '950 次，肌腱還在嗎？',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '資料庫霸主',
        emoji: '🧠📀',
        explanation: '你已經比我們還了解我們。',
        condition: 975,
        condition_description: '975 次，我們都在抄你的備份。',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '腦王降臨',
        emoji: '👑🧠',
        explanation: '你已經是這個系統的主人了。',
        condition: 990,
        condition_description: '990 次，再 10 次就統治人類了。',
        type: 'REWARD_CLAIM_TOTAL',
      },
      {
        name: '一千腦的孤獨',
        emoji: '📖🧠',
        explanation: '你已經超越人類的孤獨了。',
        condition: 1000,
        condition_description: '1000 次，你還需要我們嗎？',
        type: 'REWARD_CLAIM_TOTAL',
      },
      // special API
      {
        name: '離線潛逃',
        emoji: '🚪',
        explanation: '悄悄退出聊天室，不帶走一片雲彩。',
        condition: 1,
        condition_description: '打了留言，卻沒有發送出去就離開了討論區區',
        type: 'DRAFT_ABANDON',
      },
      {
        name: '來都來了哥',
        emoji: '🧔‍♂️',
        explanation: '幾天沒見，路過行過不要錯過，看看不同立場新聞吧!',
        condition: 1,
        condition_description: '不間斷登入',
        type: 'REAPPEARANCE',
      },
      {
        name: '閃現離場',
        emoji: '⚡️',
        explanation: '來無影去無蹤，連AI都還沒反應過來你就下線了。',
        condition: 1,
        condition_description: '入屏後少於5秒內離開見方App',
        type: 'QUICK_EXIT',
      },

      {
        name: '夜行者',
        emoji: '🌙🦇',
        explanation: '你半夜在看新聞，見方都想請你早點睡。',
        condition: 5,
        condition_description: '凌晨1點～4點間登入5次以上',
        type: 'NIGHT_LOGIN_TOTAL',
      },
    ];

    for (const title of titles) {
      await this.db
        .insertInto('title')
        .values(title)
        .onConflict((oc) => oc.column('name').doNothing())
        .execute();
    }

    console.log('✅ Titles seeded.');
  }
}
